// Licence verification for AWI Resolve.
//
// Deliberately enforced HERE, in the orchestrator, and not in the agent. The
// agent runs on the customer's own PC, so anything it decides can be patched
// out; the AI technician — the part they are actually paying for — runs on our
// side. Checking here means a licence check is worth something.
//
// The scheme matches FleetBoost's, which is already in the field: an ECDSA
// P-256 / SHA-256 signature over a JSON payload, verified offline against a
// public key baked into this file. The private key never leaves Alpha Web.
// Licences are pasteable strings (RSLIC1-<base64url>) rather than files, because
// asking a customer to save an attachment into a folder they have never heard of
// is the step most likely to end in a support call.

const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const activations = require('./activations');

const PREFIX = 'RSLIC1-';
const HOUR_MS = 3600000;

// Alpha Web licence-signing public key (SPKI, base64). Generated by
// tools/licgen.js --init; the matching private key stays internal.
const PUBLIC_KEY_SPKI_B64 = loadPublicKey();

function loadPublicKey() {
  // Kept in a file rather than inline so the generator can create it on first
  // run without anyone hand-editing source.
  const p = path.join(__dirname, 'licensing-key.pub');
  try { return fs.readFileSync(p, 'utf8').trim(); } catch { return ''; }
}

// ---- plan definitions -------------------------------------------------------
// What a plan is allowed to do. Read-only diagnostics are deliberately available
// even with no licence at all: a customer mid-incident should never be left
// unable to find out what is wrong, and it makes the trial genuinely useful.
const PLANS = {
  none:     { label: 'Unlicensed',      diagnostics: true, fixes: false, deployment: false, security: false, fullSupport: false },
  trial:    { label: 'Trial',           diagnostics: true, fixes: true,  deployment: true,  security: true,  fullSupport: false },
  // One-off paid pass. Bounded by a window of TIME that starts on first use
  // (see validForHours below) plus a small ticket allowance in the ledger.
  //
  // Deliberately FULLY LOADED. The pass exists to show a prospect what the
  // product does, and a demo that quietly withholds the most persuasive feature
  // is a bad demo — it was also, absurdly, less capable than the free trial,
  // which grants deployment. The bounds that matter are time and tickets, both
  // of which the customer can see; capability limits they cannot see just make
  // the product look weaker than it is.
  //
  // fullSupport here does NOT open consented PowerShell on its own: that is
  // dual-gated and still needs the org admin to enable it (org-library
  // allowFullItSupport, off by default). This only means a prospect who wants
  // to evaluate that tier is not blocked by the licence.
  incident: { label: '24-hour pass',    diagnostics: true, fixes: true,  deployment: true,  security: true,  fullSupport: true  },
  standard: { label: 'Standard',        diagnostics: true, fixes: true,  deployment: false, security: true,  fullSupport: false },
  pro:      { label: 'Pro',             diagnostics: true, fixes: true,  deployment: true,  security: true,  fullSupport: false },
  // Full IT Support — allowlisted tools PLUS consented PowerShell (org admin must also enable).
  full:     { label: 'Full IT Support', diagnostics: true, fixes: true,  deployment: true,  security: true,  fullSupport: true },
};

// The descriptive half of a licence: whose it is, who holds it, and what name
// their support window should carry. Shared by every return path below so an
// EXPIRED licence still reports its own details — a renewal conversation is
// precisely the moment the customer needs to see whose licence lapsed.
//
// brandName falls back to the billing name, so co-branding works for every key
// ever issued without anyone having to re-issue one.
function identity(p) {
  return {
    customer: p.customer || null,
    customerId: p.customerId || null,
    licensedTo: p.licensedTo || null,
    licensedToEmail: p.licensedToEmail || null,
    brandName: p.brandName || p.customer || null,
    licenseId: p.licenseId || null,
    seats: p.seats || 1,
    issuedAt: p.issuedAt || null,
  };
}

function decode(key) {
  if (!key || typeof key !== 'string') return { ok: false, error: 'no licence key' };
  // Tolerant on purpose — keys arrive pasted out of emails and chat, so
  // whitespace, line breaks and a missing prefix are all forgiven. Being strict
  // would only ever punish an honest customer.
  let text = key.replace(/\s+/g, '');
  if (text.toUpperCase().startsWith(PREFIX)) text = text.slice(PREFIX.length);
  try {
    const json = Buffer.from(text.replace(/-/g, '+').replace(/_/g, '/'), 'base64').toString('utf8');
    const obj = JSON.parse(json);
    if (!obj || !obj.payload || !obj.signature) return { ok: false, error: 'licence key is malformed' };
    return { ok: true, envelope: obj };
  } catch {
    return { ok: false, error: 'licence key is malformed' };
  }
}

function verifySignature(envelope) {
  if (!PUBLIC_KEY_SPKI_B64) return { ok: false, error: 'no signing key installed on the service' };
  try {
    const pub = crypto.createPublicKey({
      key: Buffer.from(PUBLIC_KEY_SPKI_B64, 'base64'),
      format: 'der',
      type: 'spki',
    });
    const data = Buffer.from(JSON.stringify(envelope.payload), 'utf8');
    const sig = Buffer.from(envelope.signature, 'base64');
    const ok = crypto.verify('sha256', data, { key: pub, dsaEncoding: 'der' }, sig);
    return ok ? { ok: true } : { ok: false, error: 'licence signature is not valid' };
  } catch (e) {
    return { ok: false, error: `licence could not be verified: ${e.message}` };
  }
}

// Evaluate a licence for a specific device at a specific moment. `now` is passed
// in rather than read from the clock so this is testable.
function evaluate(key, deviceId, now = new Date()) {
  const unlicensed = (reason) => ({
    valid: false, plan: 'none', caps: PLANS.none, reason,
  });

  const d = decode(key);
  if (!d.ok) return unlicensed(d.error);
  const v = verifySignature(d.envelope);
  if (!v.ok) return unlicensed(v.error);

  const p = d.envelope.payload;
  const caps = PLANS[p.plan] || PLANS.none;
  if (!PLANS[p.plan]) return unlicensed(`unknown plan "${p.plan}"`);

  // Two kinds of licence live here.
  //
  // A SUBSCRIPTION carries an absolute expiresAt and runs from issue — the
  // original behaviour, and still what every annual plan does.
  //
  // A TIME-BOXED licence (the 24-hour pass) carries validForHours instead. Its
  // clock starts on first use, so for it `expiresAt` means something different:
  // the deadline by which it must be STARTED, not the end of the usable window.
  // Selling a day of support and having it drain while the email sits unread is
  // the sort of thing a customer only discovers at the worst moment.
  const hours = Number(p.validForHours) || 0;
  const timeBoxed = hours > 0;
  const deadline = p.expiresAt ? new Date(p.expiresAt) : null;
  const startedIso = timeBoxed ? activations.startedAt(p.licenseId) : null;

  let expires = deadline;
  if (timeBoxed) {
    if (startedIso) {
      expires = new Date(new Date(startedIso).getTime() + hours * HOUR_MS);
    } else if (deadline && now > deadline) {
      // Never used, and the window to start it has closed.
      return {
        valid: false, plan: 'none', caps: PLANS.none, expired: true,
        ...identity(p), expiresAt: p.expiresAt, validForHours: hours,
        reason: `this pass was never used and lapsed on ${String(p.expiresAt).slice(0, 10)}`,
      };
    } else {
      // Issued but not yet started — nothing is counting down.
      expires = null;
    }
  }

  if (expires && now > expires) {
    // Expired licences fall back to diagnostics rather than locking the tool —
    // the customer can still find out what is wrong while renewal is sorted.
    const iso = expires.toISOString();
    return {
      valid: false, plan: 'none', caps: PLANS.none, expired: true,
      ...identity(p), expiresAt: iso, validForHours: hours || undefined,
      startedAt: startedIso || undefined,
      reason: timeBoxed
        ? `this ${hours}-hour pass ran out at ${iso.slice(11, 16)} UTC on ${iso.slice(0, 10)}`
        : `licence expired on ${iso.slice(0, 10)}`,
    };
  }

  // Device binding is optional: a licence with no deviceIds is a floating
  // seat-count licence, policed by the seat registry instead.
  if (Array.isArray(p.deviceIds) && p.deviceIds.length && !p.deviceIds.includes(deviceId)) {
    return unlicensed('this licence is not issued for this device');
  }

  const daysLeft = expires ? Math.ceil((expires - now) / 86400000) : null;
  return {
    valid: true,
    plan: p.plan,
    caps,
    ...identity(p),
    // The effective end of cover, which for a started pass is derived from
    // first use rather than taken from the payload.
    expiresAt: expires ? expires.toISOString() : null,
    daysLeft,
    // Only meaningful for a time-boxed licence; left undefined otherwise so
    // nothing downstream has to special-case a subscription.
    ...(timeBoxed ? {
      timeBoxed: true,
      validForHours: hours,
      startedAt: startedIso,
      // Not started yet: the pass is fully usable and nothing is ticking.
      hoursLeft: expires ? Math.max(0, (expires - now) / HOUR_MS) : hours,
      activationDeadline: deadline ? deadline.toISOString() : null,
    } : {}),
    reason: null,
  };
}

/**
 * Start the clock on a time-boxed licence, if it has not started already.
 *
 * Called at the moment a customer actually asks Resolve for something — not at
 * enrollment. Pasting a key and getting set up should not spend the window they
 * paid for; the first real request should.
 *
 * Safe to call on any licence: subscriptions and invalid keys are no-ops.
 */
function beginIfTimeBoxed(key, deviceId, now = new Date()) {
  const d = decode(key);
  if (!d.ok) return { started: false, isNew: false };
  if (!verifySignature(d.envelope).ok) return { started: false, isNew: false };

  const p = d.envelope.payload;
  if (!(Number(p.validForHours) > 0) || !p.licenseId) {
    return { started: false, isNew: false };
  }
  const rec = activations.start(p.licenseId, now, { deviceId, customer: p.customer });
  return {
    started: true,
    isNew: rec.isNew,
    startedAt: rec.startedAt,
    validForHours: Number(p.validForHours),
    licenseId: p.licenseId,
  };
}

module.exports = { evaluate, beginIfTimeBoxed, decode, verifySignature, PLANS, PREFIX };
