// Licence verification for AWI Resolve.
//
// Deliberately enforced HERE, in the orchestrator, and not in the agent. The
// agent runs on the customer's own PC, so anything it decides can be patched
// out; the AI technician — the part they are actually paying for — runs on our
// side. Checking here means a licence check is worth something.
//
// The scheme matches FleetBoost's, which is already in the field: an ECDSA
// P-256 / SHA-256 signature over a JSON payload, verified offline against a
// public key baked into this file. The private key never leaves Alpha Web.
// Licences are pasteable strings (RSLIC1-<base64url>) rather than files, because
// asking a customer to save an attachment into a folder they have never heard of
// is the step most likely to end in a support call.

const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

const PREFIX = 'RSLIC1-';

// Alpha Web licence-signing public key (SPKI, base64). Generated by
// tools/licgen.js --init; the matching private key stays internal.
const PUBLIC_KEY_SPKI_B64 = loadPublicKey();

function loadPublicKey() {
  // Kept in a file rather than inline so the generator can create it on first
  // run without anyone hand-editing source.
  const p = path.join(__dirname, 'licensing-key.pub');
  try { return fs.readFileSync(p, 'utf8').trim(); } catch { return ''; }
}

// ---- plan definitions -------------------------------------------------------
// What a plan is allowed to do. Read-only diagnostics are deliberately available
// even with no licence at all: a customer mid-incident should never be left
// unable to find out what is wrong, and it makes the trial genuinely useful.
const PLANS = {
  none:     { label: 'Unlicensed',      diagnostics: true, fixes: false, deployment: false, security: false, fullSupport: false },
  trial:    { label: 'Trial',           diagnostics: true, fixes: true,  deployment: true,  security: true,  fullSupport: false },
  // One-off paid pass, sold per incident. Deliberately bounded by TIME, not by
  // "one session": the licence model counts days, and nothing anywhere counts
  // sessions — so a plan sold as single-session would be unenforceable, and a
  // promise we cannot keep is worse than a simpler one we can. Same safety
  // envelope as Standard.
  incident: { label: '24-hour pass',    diagnostics: true, fixes: true,  deployment: false, security: true,  fullSupport: false },
  standard: { label: 'Standard',        diagnostics: true, fixes: true,  deployment: false, security: true,  fullSupport: false },
  pro:      { label: 'Pro',             diagnostics: true, fixes: true,  deployment: true,  security: true,  fullSupport: false },
  // Full IT Support — allowlisted tools PLUS consented PowerShell (org admin must also enable).
  full:     { label: 'Full IT Support', diagnostics: true, fixes: true,  deployment: true,  security: true,  fullSupport: true },
};

function decode(key) {
  if (!key || typeof key !== 'string') return { ok: false, error: 'no licence key' };
  // Tolerant on purpose — keys arrive pasted out of emails and chat, so
  // whitespace, line breaks and a missing prefix are all forgiven. Being strict
  // would only ever punish an honest customer.
  let text = key.replace(/\s+/g, '');
  if (text.toUpperCase().startsWith(PREFIX)) text = text.slice(PREFIX.length);
  try {
    const json = Buffer.from(text.replace(/-/g, '+').replace(/_/g, '/'), 'base64').toString('utf8');
    const obj = JSON.parse(json);
    if (!obj || !obj.payload || !obj.signature) return { ok: false, error: 'licence key is malformed' };
    return { ok: true, envelope: obj };
  } catch {
    return { ok: false, error: 'licence key is malformed' };
  }
}

function verifySignature(envelope) {
  if (!PUBLIC_KEY_SPKI_B64) return { ok: false, error: 'no signing key installed on the service' };
  try {
    const pub = crypto.createPublicKey({
      key: Buffer.from(PUBLIC_KEY_SPKI_B64, 'base64'),
      format: 'der',
      type: 'spki',
    });
    const data = Buffer.from(JSON.stringify(envelope.payload), 'utf8');
    const sig = Buffer.from(envelope.signature, 'base64');
    const ok = crypto.verify('sha256', data, { key: pub, dsaEncoding: 'der' }, sig);
    return ok ? { ok: true } : { ok: false, error: 'licence signature is not valid' };
  } catch (e) {
    return { ok: false, error: `licence could not be verified: ${e.message}` };
  }
}

// Evaluate a licence for a specific device at a specific moment. `now` is passed
// in rather than read from the clock so this is testable.
function evaluate(key, deviceId, now = new Date()) {
  const unlicensed = (reason) => ({
    valid: false, plan: 'none', caps: PLANS.none, reason,
  });

  const d = decode(key);
  if (!d.ok) return unlicensed(d.error);
  const v = verifySignature(d.envelope);
  if (!v.ok) return unlicensed(v.error);

  const p = d.envelope.payload;
  const caps = PLANS[p.plan] || PLANS.none;
  if (!PLANS[p.plan]) return unlicensed(`unknown plan "${p.plan}"`);

  const expires = p.expiresAt ? new Date(p.expiresAt) : null;
  if (expires && now > expires) {
    // Expired licences fall back to diagnostics rather than locking the tool —
    // the customer can still find out what is wrong while renewal is sorted.
    return {
      valid: false, plan: 'none', caps: PLANS.none, expired: true,
      customer: p.customer, expiresAt: p.expiresAt,
      reason: `licence expired on ${String(p.expiresAt).slice(0, 10)}`,
    };
  }

  // Device binding is optional: a licence with no deviceIds is a floating
  // seat-count licence, policed by the seat registry instead.
  if (Array.isArray(p.deviceIds) && p.deviceIds.length && !p.deviceIds.includes(deviceId)) {
    return unlicensed('this licence is not issued for this device');
  }

  const daysLeft = expires ? Math.ceil((expires - now) / 86400000) : null;
  return {
    valid: true,
    plan: p.plan,
    caps,
    customer: p.customer,
    customerId: p.customerId || null,
    seats: p.seats || 1,
    licenseId: p.licenseId,
    expiresAt: p.expiresAt || null,
    daysLeft,
    reason: null,
  };
}

module.exports = { evaluate, decode, verifySignature, PLANS, PREFIX };
